## Uncomment below for live, comment out for local dev
#baseurl: "/interactivate"
collections:
  activities:
    output: true
  list-pages:
    output: true
    permalink: /:name
    sort_by: jump-to-index
defaults:
 - scope:
     path: ""
     type: "activities"
   values:
     layout: "activity"
 - scope:
     path: ""
     type: "list-pages"
   values:
     layout: "list-page"
exclude:
  - "exclude"
include:
  - "_3dtransmographer"
## Uncomment two lines below for live, comment out for local dev
#sass:
#  style: compressed
tab-img-dir: "img/activities/tabs"
## Uncomment below for live, comment out for local dev
#url: "https://shodor-education.github.io/"
