## Uncomment below for live, comment out for local dev
baseurl: "/interactivate"
collections:
  activities:
    output: true
    permalink: "/activities/:name"
    sort_by: "title"
  audience-catalogs:
    output: true
    permalink: "/:name/byAudience"
  dictionary-sections:
    output: true
    permalink: "/dictionary/:name"
  discussions:
    output: true
    permalink: "/discussions/:name"
    sort_by: "title"
  lessons:
    output: true
    permalink: "/lessons/:name"
    sort_by: "title"
  main-catalogs:
    output: true
    permalink: "/:name"
    sort_by: "jump-to-index"
  standards-grade-bands:
    output: true
    permalink: "/standards/organization/:name"
    sort_by: "index"
  standards-objectives:
    output: true
    permalink: "/standards/organization/objective/:name"
    sort_by: "description"
  textbook-sections:
    output: true
    permalink: "/textbooks/section/:name"
  textbooks:
    output: true
    permalink: "/textbooks/:name"
    sort_by: "index"
  worksheets:
    output: false
    permalink: "/media/worksheets/:name"
defaults:
  - scope:
      type: "activities"
    values:
      layout: "activity"
  - scope:
      type: "audience-catalogs"
    values:
      layout: "catalog"
      subject-audience-sorter: true
  - scope:
      type: "dictionary-sections"
    values:
      catalog-type: "dictionary-terms"
      has-additional-breadcrumbs: true
      layout: "catalog"
  - scope:
      type: "discussions"
    values:
      layout: "discussion"
  - scope:
      type: "lessons"
    values:
      layout: "lesson"
  - scope:
      type: "main-catalogs"
    values:
      layout: "catalog"
  - scope:
      type: "standards-grade-bands"
    values:
      catalog-type: "standards-objectives"
      has-additional-breadcrumbs: true
      layout: "catalog"
  - scope:
      type: "standards-objectives"
    values:
      catalog-type: "standards-aligned-resources"
      has-additional-breadcrumbs: true
      layout: "catalog"
      page-description: true
      title: "Aligned Resources"
  - scope:
      type: "textbook-sections"
    values:
      catalog-type: "textbook-aligned-resources"
      has-additional-breadcrumbs: true
      layout: "catalog"
      page-description: true
  - scope:
      type: "textbooks"
    values:
      catalog-type: "textbook-sections"
      layout: "catalog"
exclude:
  - "exclude"
include:
  - "_3dtransmographer"
plugins:
  - "jekyll-redirect-from"
## Uncomment two lines below for live, comment out for local dev
#sass:
#  style: compressed
tab-img-dir: "img/activities/tabs"
## Uncomment below for live, comment out for local dev
#url: "https://shodor-education.github.io/"
whitelist:
  - "jekyll-redirect-from"
