## Uncomment below for live, comment out for local dev
#baseurl: "/interactivate"
collections:
  activities:
    output: true
  list-pages:
    output: true
defaults:
 - scope:
     path: ""
     type: "activities"
   values:
     layout: "activity"
exclude:
  - "exclude"
include:
  - "_3dtransmographer"
## Uncomment two lines below for live, comment out for local dev
#sass:
#  style: compressed
tab-img-dir: "img/activities/tabs"
## Uncomment below for live, comment out for local dev
#url: "https://shodor-education.github.io/"
