#baseurl: "/interactivate"
collections:
  activities:
    output: true
  subdirectories:
    output: true
defaults:
 - scope:
     path: ""
     type: "activities"
   values:
     layout: "activity"
exclude:
  - "exclude"
include:
  - "_3dtransmographer"
tab-img-dir: "img/activities/tabs/"
#url: "https://shodor-education.github.io/"
