## Uncomment below for live, comment out for local dev
baseurl: "/interactivate"
collections:
  activities:
    output: true
  audience-catalogs:
    output: true
    permalink: "/:name/byAudience"
  catalogs:
    output: true
    permalink: "/:name"
    sort_by: "jump-to-index"
  dictionary-sections:
    output: true
    permalink: "/dictionary/:name"
defaults:
  - scope:
      path: ""
      type: "activities"
    values:
      layout: "activity"
  - scope:
      path: ""
      type: "audience-catalogs"
    values:
      categories-list-name: "audiences"
      categories-list-type: "data"
      filter-by: "audience"
      layout: "catalog"
  - scope:
      path: ""
      type: "catalogs"
    values:
      layout: "catalog"
  - scope:
      path: ""
      type: "dictionary-sections"
    values:
      additional-breadcrumb-link: "dictionary"
      additional-breadcrumb-title: "Dictionary"
      categories-list-type: "page-title-only"
      catalog-items-list-name: "dictionary-sections"
      catalog-items-list-type: "collection"
      catalog-item-name: "dictionary-term"
      catalog-vars-include-file: "catalog-vars/dictionary-section-catalog-vars.html"
      layout: "catalog"
exclude:
  - "exclude"
include:
  - "_3dtransmographer"
plugins:
  - "jekyll-redirect-from"
## Uncomment two lines below for live, comment out for local dev
#sass:
#  style: compressed
tab-img-dir: "img/activities/tabs"
## Uncomment below for live, comment out for local dev
#url: "https://shodor-education.github.io/"
whitelist:
  - "jekyll-redirect-from"
