## Uncomment below for live, comment out for local dev
#baseurl: "/interactivate"
collections:
  activities:
    output: true
  audience-catalogs:
    output: true
    permalink: /:name/byAudience
  catalogs:
    output: true
    permalink: /:name
    sort_by: jump-to-index
  subject-catalogs:
    output: true
    permalink: /:name/bySubject
defaults:
 - scope:
     path: ""
     type: "activities"
   values:
     layout: "activity"
 - scope:
     path: ""
     type: "audience-catalogs"
   values:
     layout: "audience-catalog"
 - scope:
     path: ""
     type: "catalogs"
   values:
     layout: "catalog"
 - scope:
     path: ""
     type: "subject-catalogs"
   values:
     layout: "subject-catalog"
exclude:
  - "exclude"
include:
  - "_3dtransmographer"
## Uncomment two lines below for live, comment out for local dev
#sass:
#  style: compressed
tab-img-dir: "img/activities/tabs"
## Uncomment below for live, comment out for local dev
#url: "https://shodor-education.github.io/"
