## Uncomment below for live, comment out for local dev
baseurl: "/interactivate"
collections:
  activities:
    sort_by: "title"
    output: true
    permalink: "/activities/:name"
  audience-catalogs:
    output: true
    permalink: "/:name/byAudience"
  catalogs:
    output: true
    permalink: "/:name"
    sort_by: "jump-to-index"
  dictionary-sections:
    output: true
    permalink: "/dictionary/:name"
  textbook-sections:
    output: true
    permalink: "/textbooks/section/:name"
  textbooks:
    output: true
    permalink: "/textbooks/:name"
defaults:
  - scope:
      type: "activities"
    values:
      item-name: "activity"
      layout: "activity"
  - scope:
      type: "audience-catalogs"
    values:
      layout: "catalog"
      subject-audience-sorter: true
  - scope:
      type: "catalogs"
    values:
      layout: "catalog"
  - scope:
      type: "dictionary-sections"
    values:
      item-name: "dictionary-section"
      layout: "catalog"
  - scope:
      type: "textbook-sections"
    values:
      item-name: "textbook-section"
      page-description: true
      layout: "catalog"
  - scope:
      type: "textbooks"
    values:
      item-name: "textbook"
      layout: "catalog"
exclude:
  - "exclude"
include:
  - "_3dtransmographer"
plugins:
  - "jekyll-redirect-from"
## Uncomment two lines below for live, comment out for local dev
#sass:
#  style: compressed
tab-img-dir: "img/activities/tabs"
## Uncomment below for live, comment out for local dev
#url: "https://shodor-education.github.io/"
whitelist:
  - "jekyll-redirect-from"
