## Uncomment below for live, comment out for local dev
baseurl: "/interactivate"
collections:
  activities:
    output: true
    permalink: "/activities/:name"
    sort_by: "title"
  audience-catalogs:
    output: true
    permalink: "/:name/byAudience"
  catalogs:
    output: true
    permalink: "/:name"
    sort_by: "jump-to-index"
  dictionary-sections:
    output: true
    permalink: "/dictionary/:name"
  standards-grade-bands:
    output: true
    permalink: "/standards/organization/:name"
  standards-objectives:
    output: true
    permalink: "/standards/organization/objective/:name"
  textbook-sections:
    output: true
    permalink: "/textbooks/section/:name"
  textbooks:
    output: true
    permalink: "/textbooks/:name"
defaults:
  - scope:
      type: "activities"
    values:
      item-type: "activity"
      layout: "activity"
  - scope:
      type: "audience-catalogs"
    values:
      layout: "catalog"
      subject-audience-sorter: true
  - scope:
      type: "catalogs"
    values:
      layout: "catalog"
  - scope:
      type: "dictionary-sections"
    values:
      item-type: "dictionary-section"
      layout: "catalog"
  - scope:
      type: "standards-grade-bands"
    values:
      item-type: "standards-grade-band"
      layout: "catalog"
  - scope:
      type: "standards-objectives"
    values:
      item-type: "standards-objective"
      layout: "catalog"
      title: "Aligned Resources"
  - scope:
      type: "textbook-sections"
    values:
      item-type: "textbook-section"
      layout: "catalog"
      page-description: true
  - scope:
      type: "textbooks"
    values:
      item-type: "textbook"
      layout: "catalog"
exclude:
  - "exclude"
include:
  - "_3dtransmographer"
plugins:
  - "jekyll-redirect-from"
## Uncomment two lines below for live, comment out for local dev
#sass:
#  style: compressed
tab-img-dir: "img/activities/tabs"
## Uncomment below for live, comment out for local dev
#url: "https://shodor-education.github.io/"
whitelist:
  - "jekyll-redirect-from"
