## Uncomment below for live, comment out for local dev
baseurl: "/interactivate"
collections:
  activities:
    sort_by: "title"
    output: true
  audience-catalogs:
    output: true
    permalink: "/:name/byAudience"
  catalogs:
    output: true
    permalink: "/:name"
    sort_by: "jump-to-index"
  dictionary-sections:
    output: true
    permalink: "/dictionary/:name"
  textbook-sections:
    output: true
    permalink: "/textbooks/section/:name"
  textbooks:
    output: true
defaults:
  - scope:
      type: "activities"
    values:
      additional-breadcrumb-link: "activities"
      additional-breadcrumb-title: "Activities"
      layout: "activity"
  - scope:
      type: "audience-catalogs"
    values:
      layout: "catalog"
      subject-audience-sorter: true
  - scope:
      type: "catalogs"
    values:
      layout: "catalog"
  - scope:
      type: "dictionary-sections"
    values:
      additional-breadcrumb-link: "dictionary"
      additional-breadcrumb-title: "Dictionary"
      catalog-vars-include-file: "catalog-vars/dictionary-section-catalog-vars.html"
      layout: "catalog"
  - scope:
      type: "textbooks"
    values:
      additional-breadcrumb-link: "textbooks"
      additional-breadcrumb-title: "Textbooks"
      catalog-vars-include-file: "catalog-vars/textbook-catalog-vars.html"
      layout: "catalog"
exclude:
  - "exclude"
include:
  - "_3dtransmographer"
plugins:
  - "jekyll-redirect-from"
## Uncomment two lines below for live, comment out for local dev
#sass:
#  style: compressed
tab-img-dir: "img/activities/tabs"
## Uncomment below for live, comment out for local dev
#url: "https://shodor-education.github.io/"
whitelist:
  - "jekyll-redirect-from"
